language: ruby
rvm:
  - 2.5.1
addons:
  chrome: stable
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake
